# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(max_length=10)),
                ('y', models.FloatField(max_length=10)),
                ('attribute', models.CharField(max_length=20)),
            ],
        ),
    ]
